### ISSUE TITLE
##[error]File not found: 'C:\Build\_work\_tasks\SecureFilesToBuildDir_036b2893-18f0-43f3-afd1-1803f0ac5313\1.0.0\index.js'

### ISSUE THREAD

**Issue by Mertsch** [sverigesradio/tfs-copy-secure-file#1]
I am getting `##[error]File not found: 'C:\Build\_work\_tasks\SecureFilesToBuildDir_036b2893-18f0-43f3-afd1-1803f0ac5313\1.0.0\index.js'` during build.

The folder only contains `task.json`

Using VSTS and https://marketplace.visualstudio.com/items?itemName=playx.securefiles-to-builddir

**Comment by BoneGoat** [comment]
We're using it for our builds on VSTS and it works fine. Have you tried removing the exension and re-adding it?

**Comment by Mertsch** [comment]
@BoneGoat I have removed and readded the extension, I have also deleted all my build tasks and forced a re-download, no difference.

I noticed that when you Download the 1.0.0 package it contains an outdated `extension.vsomanifest` which does, in its content, not point to any files compared to the `extension.vsixmanifest`

It seems you have uploaded 1.0.0 before its current state. Can you release a 1.0.1 with updated content?!

**Comment by BoneGoat** [comment]
@Mertsch Please explain why the manifest is outdated and which files it's supposed to point to.

**Comment by Mertsch** [comment]
@BoneGoat when downloading the package off the market place
https://marketplace.visualstudio.com/_apis/gallery/publishers/playx/extensions/securefiles-to-builddir/1.0.0/package?noPrompt=true
I am getting a package which does not match the content of this repo.

Most notably:
this repo has https://github.com/sverigesradio/tfs-copy-secure-file/blob/master/index.ts <-- `ts`
the VISX has `index.js` <-- `js` (which is additionally not located in the `buildtask` folder

That is why I think the VSIX is not current with the actual source code

**Comment by BoneGoat** [comment]
Project is written in Typescript and transpiled into JS. Archiving this project.
